In [1]:
import numpy as np
from colossus.cosmology import cosmology
import readgadget
from tetrahedrafunc import *

QuijoteFid = {'H0': 67.11,
 'Ob0': 0.049, 
 'Om0': 0.3175,
 'flat': True,
 'ns': 0.9624,
 'sigma8': 0.834}
mycosmos =  cosmology.setCosmology("QuijoteFid", **QuijoteFid)

In [38]:
z = np.linspace(0,50,10000)
scales = mycosmos.growthFactor(z)

In [39]:
uniformlogscales100 = np.linspace(max(np.log(scales)),min(np.log(scales)),100)

In [40]:
uniformlogscales100

array([-3.17216526e-05, -3.72561225e-02, -7.44805234e-02, -1.11704924e-01,
       -1.48929325e-01, -1.86153726e-01, -2.23378127e-01, -2.60602528e-01,
       -2.97826929e-01, -3.35051329e-01, -3.72275730e-01, -4.09500131e-01,
       -4.46724532e-01, -4.83948933e-01, -5.21173334e-01, -5.58397735e-01,
       -5.95622135e-01, -6.32846536e-01, -6.70070937e-01, -7.07295338e-01,
       -7.44519739e-01, -7.81744140e-01, -8.18968540e-01, -8.56192941e-01,
       -8.93417342e-01, -9.30641743e-01, -9.67866144e-01, -1.00509054e+00,
       -1.04231495e+00, -1.07953935e+00, -1.11676375e+00, -1.15398815e+00,
       -1.19121255e+00, -1.22843695e+00, -1.26566135e+00, -1.30288575e+00,
       -1.34011015e+00, -1.37733455e+00, -1.41455895e+00, -1.45178336e+00,
       -1.48900776e+00, -1.52623216e+00, -1.56345656e+00, -1.60068096e+00,
       -1.63790536e+00, -1.67512976e+00, -1.71235416e+00, -1.74957856e+00,
       -1.78680296e+00, -1.82402736e+00, -1.86125176e+00, -1.89847617e+00,
       -1.93570057e+00, -

In [41]:
uniformscalezs = []

cur = 0
for idx in range(len(scales)):
    if np.log(scales[idx]) <= uniformlogscales100[cur]:
        uniformscalezs.append(z[idx])
        cur +=1



In [42]:
uniformscalezs

[0.0,
 0.075007500750075,
 0.14001400140014003,
 0.21002100210021002,
 0.28002800280028006,
 0.35003500350035005,
 0.42504250425042506,
 0.4950495049504951,
 0.57005700570057,
 0.6450645064506451,
 0.7200720072007201,
 0.8000800080008001,
 0.8800880088008801,
 0.9650965096509652,
 1.05010501050105,
 1.1351135113511353,
 1.2251225122512253,
 1.3201320132013201,
 1.4151415141514152,
 1.5151515151515151,
 1.6151615161516153,
 1.7201720172017203,
 1.8301830183018302,
 1.9401940194019403,
 2.055205520552055,
 2.1802180218021805,
 2.3002300230023005,
 2.43024302430243,
 2.5652565256525652,
 2.7052705270527055,
 2.8452845284528454,
 2.9952995299529954,
 3.1503150315031503,
 3.3103310331033104,
 3.4753475347534755,
 3.6453645364536453,
 3.8253825382538253,
 4.010401040104011,
 4.2004200420042,
 4.400440044004401,
 4.605460546054606,
 4.820482048204821,
 5.0405040504050405,
 5.275527552755276,
 5.510551055105511,
 5.7605760576057605,
 6.020602060206021,
 6.285628562856286,
 6.565656565656566,
 

In [43]:
len(uniformscalezs)

100

In [44]:
uniformscalezs = np.array(uniformscalezs)

In [47]:
np.log(mycosmos.growthFactor(uniformscalezs))[1::] - np.log(mycosmos.growthFactor(uniformscalezs))[0:-1]

array([-0.03988311, -0.03471802, -0.03739023, -0.03722238, -0.0369093 ,
       -0.03906721, -0.0359173 , -0.03782641, -0.03710579, -0.03635022,
       -0.03790666, -0.03697992, -0.03825203, -0.03720427, -0.03619035,
       -0.03724672, -0.03815196, -0.0369865 , -0.03770734, -0.03650964,
       -0.03711771, -0.03762008, -0.03639381, -0.03680414, -0.03863511,
       -0.03582135, -0.03749317, -0.03758109, -0.03760915, -0.03630851,
       -0.03755   , -0.0374254 , -0.03726119, -0.03706273, -0.03683415,
       -0.0376054 , -0.03725513, -0.03689042, -0.03743323, -0.03698123,
       -0.03737934, -0.03686169, -0.0379349 , -0.03655332, -0.03748031,
       -0.03755254, -0.03688108, -0.03754643, -0.03682138, -0.03734724,
       -0.03718108, -0.0369875 , -0.03731424, -0.03755325, -0.03720579,
       -0.03684365, -0.03741284, -0.03696554, -0.03739408, -0.03730525,
       -0.03717171, -0.03738992, -0.03715632, -0.03725971, -0.03695501,
       -0.03730905, -0.03725031, -0.03714496, -0.0372998 , -0.03

In [52]:
ts = 1.0/(1+uniformscalezs)

In [55]:
with open("uniscale_times.dat","w") as f:
    for t in ts[::-1]:
        f.write("%.6f\n"%t)

In [54]:
ts[::-1]

array([0.01960784, 0.02035838, 0.02113735, 0.02194693, 0.0227872 ,
       0.02365793, 0.02456159, 0.02550121, 0.02647697, 0.02748874,
       0.02853604, 0.02962675, 0.03075678, 0.03193049, 0.0331478 ,
       0.03441416, 0.0357236 , 0.03708842, 0.03850227, 0.03997218,
       0.0414898 , 0.04307148, 0.04471845, 0.04642083, 0.04818818,
       0.05003277, 0.05194313, 0.05391779, 0.05597009, 0.05811716,
       0.06032616, 0.06263115, 0.06501343, 0.06749286, 0.07007057,
       0.07272053, 0.07549321, 0.07836268, 0.08135949, 0.08445173,
       0.08767284, 0.09102495, 0.09446476, 0.09807845, 0.10177203,
       0.10564295, 0.1096995 , 0.11388512, 0.11819289, 0.12268862,
       0.12737742, 0.13217623, 0.13725652, 0.14243793, 0.14791639,
       0.15359683, 0.15934915, 0.1655491 , 0.17180708, 0.17839747,
       0.1851701 , 0.19229216, 0.19958482, 0.20723746, 0.21526836,
       0.22344633, 0.23200074, 0.24094556, 0.25029413, 0.26005878,
       0.26988583, 0.28048473, 0.29152453, 0.30300918, 0.31444

In [64]:
[(i,np.random.randint(100000)) for i in range(16)]

[(0, 32494),
 (1, 45234),
 (2, 41242),
 (3, 25828),
 (4, 8740),
 (5, 65964),
 (6, 66097),
 (7, 47916),
 (8, 63474),
 (9, 3449),
 (10, 24743),
 (11, 65286),
 (12, 41162),
 (13, 47858),
 (14, 77274),
 (15, 78884)]